#include <iostream>

int main() 
{
    int num, x;
    std::cout << "Type a integer number: ";
    std::cin >> num;
    x = num;

    long long fatorial = 1; // While I was trying to do this code on my own I only forgot to use long long type for factorial.
    while (x > 1) { // Factorials value increase very quickly, so standard types aren't big enough.
        fatorial *= x;
        x--;
    }

    std::cout << "The factorial of " << num << " is " << fatorial << "\n";

    system("PAUSE");

    // Answer generated by Microsoft's Copilot. It was only missing showing which number was used to calculate the factorial and a few minor settings.  
}
